config/routes.rb
Bank::Application.routes.draw do
  get "welcome/index"
  
  resources :transfers
  resources :deposits
  resources :withdraws

root :to => 'welcome#index'

end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  attr_accessible :amount, :user_id
  validates :amount, :numericality => { :greater_than => 0 }
  belongs_to :sender, :class_name => 'User', :foreign_key => 'user_id'
  def init(amount, user_id)
    @user= User.find(user_id)
    transaction do
      self.amount=amount
      self.user_id=user_id
      if self.save  
        @user.deposit(amount)
        return true
      else
        return false
      end   
    end    
  end

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  attr_accessible :amount, :receiver, :sender
  validates :amount, :numericality => { :greater_than => 0 }
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :receiver, :class_name => 'User', :foreign_key => 'receiver_id'
  def init(amount, sender_id,receiver_id)
    @sender=User.find(sender_id)
    @receiver=User.find(receiver_id)
      transaction do
        self.amount=amount
        self.sender_id=sender_id
        self.receiver_id=receiver_id
        if !self.save
          return false
        end
        @receiver.deposit(amount)
        @sender.withdraw(amount)
      end
      return true
   
  
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :sent_transfers, :class_name => 'Transfer', :foreign_key => 'sender_id', :dependent => :destroy
  has_many :received_transfers, :class_name => 'Transfer', :foreign_key => 'receiver_id', :dependent => :destroy
  has_many :deposits, :class_name => 'Deposit', :foreign_key => 'user_id', :dependent => :destroy
  has_many :withdraws, :class_name => 'Withdraw', :foreign_key => 'user_id', :dependent => :destroy
  before_save :default_values
  def default_values
    self.balance ||= 0
  end
  def deposit(amount)
    self.balance=self.balance+amount
    self.save
  end
  
  def withdraw(amount)
    self.balance=self.balance-amount
    self.save
  end
  def deficit(amount)
    if self.balance<amount
      return true
    else
      return false
    end
  end
end

app/models/withdraw.rb
class Withdraw < ActiveRecord::Base
  attr_accessible :amount, :user_id
  validates :amount, :numericality => { :greater_than => 0 }
  belongs_to :sender, :class_name => 'User', :foreign_key => 'user_id'
  def init(amount, user_id)
        @user=User.find(user_id)
          transaction do
              self.amount=amount
              self.user_id=user_id
              @user.withdraw(amount)
              if !self.save
                return false
              end
          end
        return true
            
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  include Clearance::Controller
  protect_from_forgery
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def new
    @deposit = Deposit.new
  end
  def is_number?(object)
  true if Integer(object) rescue false
  end
  def create
        @deposit = Deposit.new
        if @deposit.init(deposit_params[:amount].to_i,current_user.id)
          redirect_to root_url, alert: "Amount Deposited"
        else
          flash[:notice] = "Amount Entered shall be a positive Integer"
          redirect_to :action => "new"
        end
  end
  private
  def deposit_params
    params.require(:deposit).permit(:amount)
  end

end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def new
    @transfer = Transfer.new
  end
  def is_number?(object)
  true if Integer(object) rescue false
  end
  def create
      @sender=User.find(current_user.id)
      if @sender.deficit(transfer_params[:amount].to_i)
        flash[:notice] = "The amount you entered is more than what you have, you will run into a deficit"
        redirect_to :action => "new"
      else
        @transfer = Transfer.new
        if  @transfer.init(transfer_params[:amount].to_i,current_user.id,transfer_params[:receiver_id])
            redirect_to root_url, alert: "Amount Transfered"
        else        
          flash[:notice] = "Amount Entered shall be a positive Integer"
          redirect_to :action => "new"

        end 
      end

  end
  private
  def transfer_params
    params.require(:transfer).permit(:amount, :receiver_id)
  end
end

app/controllers/users_controller.rb
class Clearance::UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:create, :new]
  before_filter :avoid_sign_in, :only => [:create, :new], :if => :signed_in?

  def new
    @user = user_from_params
    render :template => 'users/new'
  end

  def create
    @user = user_from_params
    @user.balance=0
    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render :template => 'users/new'
    end
  end

  private

  def avoid_sign_in
    redirect_to Clearance.configuration.redirect_url
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    user_params = params[:user] || Hash.new
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authorize
  def index
  end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
  def new
    @withdraw = Withdraw.new
  end
  def is_number?(object)
  true if Integer(object) rescue false
  end
  def create
      @user=User.find(current_user.id)
      if @user.deficit(withdraw_params[:amount].to_i)
          flash[:notice] = "The amount you entered is more than what you have, you will run into a deficit"
          redirect_to :action => "new"

      else
        @withdraw = Withdraw.new
        if !@withdraw.init(withdraw_params[:amount].to_i,current_user.id)
          flash[:notice] = "Amount Entered shall be a positive integer"
          redirect_to :action => "new"
        else
          redirect_to root_url, alert: "Amount Withdrawn"
        end         
      end
  end
  private
  def withdraw_params
    params.require(:withdraw).permit(:amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/deposits/new.html.erb
<h1>Deposit</h1>
<%= form_for :deposit, url: deposits_path do |f| %> 
 <p>
    <%= f.label :amount %><br>
	<input type="text" name="deposit[amount]" />
    
  </p>
 
 
 
  <p>
    <%= f.submit "Deposit Amount" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>
   <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

<%= yield %>

</body>
</html>

app/views/transfers/new.html.erb
<h1>New Transfer</h1>
<%= form_for :transfer, url: transfers_path do |f| %>  <p>
    <%= f.label :amount %><br>
	<input type="text" name="transfer[amount]" />
    
  </p>
 
  <p>
    <%= f.label :receiver %><br>	
<%= f.collection_select( :receiver_id, User.where("id NOT IN (?)", [current_user.id]), :id, :email) %>
  </p>
 
  <p>
    <%= f.submit "Transfer" %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>
<%= current_user.email %> Account</h1>
<h3>your Current Balance is : $ <%= current_user.balance %></h3> <a href="/deposits/new" >Deposit</a>  <a href="/withdraws/new" >Withdraw</a>
<a href="/transfers/new" >Transfer</a>
<h5> Your Deposits </h5>
    <% current_user.deposits.reverse.each do |element| %>

you Deposited $<%= element.amount %>  <%= element.created_at %></br>
	
<% end %>
<h5> Your Withdrawals </h5>
    <% current_user.withdraws.reverse.each do |element| %>

you have Withdrawn $<%= element.amount %>  <%= element.created_at %></br>
	
<% end %>

<h5> Your sent Transfers </h5>
    <% current_user.sent_transfers.reverse.each do |element| %>
 <%if element.receiver!=nil %>
you Transfered $<%= element.amount %> to <%= element.receiver[:email] %> <%= element.created_at %></br>
	
	<% end %>
<% end %>
<h5> Your received Transfers </h5>
    <% current_user.received_transfers.reverse.each do |element| %>
 <%if element.sender!=nil %>
you received $<%= element.amount %> from <%= element.sender[:email] %> <%= element.created_at %></br>
	
	<% end %>
<% end %>

app/views/withdraws/new.html.erb
<h1>Deposit</h1>
<%= form_for :withdraw, url: withdraws_path do |f| %> 
 <p>
    <%= f.label :amount %><br>
	<input type="text" name="withdraw[amount]" />
    
  </p>
 
 
 
  <p>
    <%= f.submit "Withdraw Amount" %>
  </p>
<% end %>